print("Merhaba Git!")
print("Git ogreniyorum")
print("GitHub'a ilk projemi gönderdim!")
print("Git calisiyorum!")
print("Bu geliştirme branch'inde yazildi.")
print("Sadece geliştirme branch'inde")
print("Pull Request denemesi")
print("Git tekrari.")
print("GitHub üzerinden değişiklik yaptim.")
